import { readFileSync, mkdirSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, resolve, relative } from 'node:path';
import ts from 'typescript';

const root = resolve(import.meta.dirname, '..');
const entries = [];
const visited = new Set();

function exported(node) {
  return Boolean(node.modifiers?.some((modifier) => modifier.kind === ts.SyntaxKind.ExportKeyword));
}

function modulePath(file, specifier) {
  const base = resolve(dirname(file), specifier);
  for (const candidate of [`${base}.ts`, resolve(base, 'index.ts')]) {
    if (existsSync(candidate)) return candidate;
  }
  throw new Error(`Cannot resolve ${specifier} from ${relative(root, file)}.`);
}

function visit(file) {
  if (visited.has(file)) return;
  visited.add(file);
  const source = readFileSync(file, 'utf8');
  const sourceFile = ts.createSourceFile(
    file,
    source,
    ts.ScriptTarget.Latest,
    true,
    ts.ScriptKind.TS,
  );
  const sourcePath = relative(root, file).replaceAll('\\', '/');

  for (const statement of sourceFile.statements) {
    if (ts.isExportDeclaration(statement)) {
      if (statement.moduleSpecifier && ts.isStringLiteralLike(statement.moduleSpecifier)) {
        const target = modulePath(file, statement.moduleSpecifier.text);
        if (!statement.exportClause) visit(target);
        if (statement.exportClause && ts.isNamedExports(statement.exportClause)) {
          for (const element of statement.exportClause.elements) {
            const localName = element.propertyName?.text ?? element.name.text;
            if (localName !== element.name.text) {
              entries.push({ kind: 'alias', name: element.name.text, sourcePath });
            }
          }
        }
      }
      continue;
    }

    if (!exported(statement)) continue;
    if (
      ts.isClassDeclaration(statement) ||
      ts.isInterfaceDeclaration(statement) ||
      ts.isTypeAliasDeclaration(statement) ||
      ts.isEnumDeclaration(statement) ||
      ts.isFunctionDeclaration(statement)
    ) {
      if (statement.name) {
        const kind = ts.isTypeAliasDeclaration(statement)
          ? 'type'
          : ts.SyntaxKind[statement.kind].replace('Declaration', '').toLowerCase();
        entries.push({ kind, name: statement.name.text, sourcePath });
      }
    } else if (ts.isVariableStatement(statement)) {
      for (const declaration of statement.declarationList.declarations) {
        if (ts.isIdentifier(declaration.name))
          entries.push({ kind: 'const', name: declaration.name.text, sourcePath });
      }
    }
  }
}

visit(resolve(root, 'projects/cornerstone/src/public-api.ts'));

const unique = [...new Map(entries.map((entry) => [entry.name, entry])).values()].sort((a, b) =>
  a.name.localeCompare(b.name),
);
const markdown = `# Public API surface\n\nGenerated by \`npm run api:generate\`.\n\n${unique.map((entry) => `- \`${entry.name}\` (${entry.kind}) — \`${entry.sourcePath}\``).join('\n')}\n`;
const json = `${JSON.stringify(unique, null, 2)}\n`;
const targets = [
  [resolve(root, 'docs/api-surface.md'), markdown],
  [resolve(root, 'design-system/src/generated/api.json'), json],
];

const check = process.argv.includes('--check');
let changed = false;
for (const [target, content] of targets) {
  if (check) {
    if (!existsSync(target) || readFileSync(target, 'utf8') !== content) {
      console.error(`Generated API output is stale: ${relative(root, target)}`);
      changed = true;
    }
  } else {
    mkdirSync(resolve(target, '..'), { recursive: true });
    writeFileSync(target, content);
  }
}
if (changed) process.exitCode = 1;
else console.log(`${unique.length} public symbols ${check ? 'verified' : 'documented'}.`);
